filename=input("Enter the file name:")
file=open(filename,'w')
data=input("Enter data to be written to the file:")
file.write(data)
file.close()
file=open(filename,'r')
contents=file.read()
file.close()
print("Contents of the file:")
print(contents)
