sentence=input("Enter a sentence:")
length=len(sentence)
words=sentence.split()
word_count=len(words)
word_to_replace=input("Enter the word to replace")
new_word=input("Enter the new word:")
modified_sentence=sentence.replace(word_to_replace,new_word)
print("Length of the sentence:",length)
print("Number of words:",word_count)
print("Modified sentence:",modified_sentence)
